### ISSUE TITLE
No documents match this query

### ISSUE THREAD

**Issue by surjithctly** [SimeonGriggs/sanity-plugin-documents-pane#1]
First of all, thanks for this awesome little plugin. This seems to be a great option to filter posts by category or authors. 

However, there's a weird bug which causes to return `No documents match this query` everytime we click the tab. Then after a second, it loads the correct data. I wish if the error only appeared if no match found. Not everytime before firing an event. 

It can be blank until the real content is loaded. 

This part:
https://github.com/SimeonGriggs/sanity-plugin-documents-pane/blob/23d235f0fe17a66fea48461056247f5572275a2d/src/DocumentsPane.js#L36-L38

**Comment by SimeonGriggs** [comment]
You're right a `loading` state either blank or with a spinner would be good. I'll attempt to circle back to this soon!

**Comment by SimeonGriggs** [comment]
Loading state (and a debug option) added in 1.0.4
