### ISSUE TITLE
Error: Pane is missing router context

### ISSUE THREAD

**Issue by visini** [SimeonGriggs/sanity-plugin-documents-pane#5]
Versions: `@sanity/base@2.30.0` and `sanity-plugin-documents-pane@^1.0.8`

Thanks for this handy plugin! 🏅 Incoming references are nicely rendered in the tab. Nice!

<img width="829" alt="Screenshot 2022-06-01 at 21 55 17" src="https://user-images.githubusercontent.com/10230606/171490378-6de1ea22-26ab-4b6b-9cef-8dfd2522384d.png">

But, I'm getting an error when trying to click on the reference to navigate to it:

<img width="633" alt="Screenshot 2022-06-01 at 21 50 25" src="https://user-images.githubusercontent.com/10230606/171489774-faaab36e-076c-4c17-a048-84a25d541a33.png">

Unfortunately, nothing really useful shows up in the browser's console:

<img width="1494" alt="Screenshot 2022-06-01 at 21 49 06" src="https://user-images.githubusercontent.com/10230606/171489812-63b1555d-46c1-4159-847a-58d0ee5abf96.png">

<img width="1497" alt="Screenshot 2022-06-01 at 21 48 49" src="https://user-images.githubusercontent.com/10230606/171489818-84b6e0c0-59f5-4d64-97cf-724e110a4c62.png">

My desk structure: 

```js
import S from "@sanity/desk-tool/structure-builder"
import DocumentsPane from "sanity-plugin-documents-pane"


export const getDefaultDocumentNode = ({ schemaType }) => {
  if (["publisher", "work"].includes(schemaType)) {
    return S.document().views([
      S.view.form(),
      S.view
        .component(DocumentsPane)
        .options({
          query: `*[!(_id in path("drafts.**")) && references($id)]`,
          params: { id: `_id` },
          useDraft: false,
          debug: true,
        })
        .title("Incoming References"),
    ])
  }
  return S.document().views([S.view.form()])
}

export default () =>
  S.list()
    .title("Content")
    .items([
      S.documentTypeListItem("publisher"),
      S.documentTypeListItem("work"),
    ])
```

What am I missing? Happy to help debug this...

**Comment by SimeonGriggs** [comment]
Are you using the latest version of the Studio?

And is the plugin symlinked or installed normally?

**Comment by TedSanne** [comment]
Having the same problem. Using the latest versions:
@sanity/cli             2.30.0 (up to date)
@sanity/base            2.30.1 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.30.1 (up to date)
@sanity/default-layout  2.30.1 (up to date)
@sanity/default-login   2.30.1 (up to date)
@sanity/desk-tool       2.30.1 (up to date)
@sanity/vision          2.30.1 (up to date)

**Comment by SimeonGriggs** [comment]
Hey @TedSanne @visini if you're still getting this issue – could you try deleting `node_modules` and doing a fresh install? I have a feeling this bug occurs when dependencies get misaligned and perhaps there's multiple router contexts.

**Comment by TedSanne** [comment]
@SimeonGriggs That worked for me!

**Comment by SimeonGriggs** [comment]
Great thanks for confirming.

I've made some changes in a new release today (`1.0.9`) which hopefully should prevent this from happening again.
